### ISSUE TITLE
Find a scalable way to get features from MongoDB to the client.

### ISSUE THREAD

**Issue by garnertb** [garnertb/rogue_geonode#12]
Ideally we could make tiled requests to the mongodb geospatial index and get a list of features back as JSON documents.

**Comment by ajayers** [comment]
Is the thought behind tiling the requests due to the number and/or complexity of the features? I think taking a deep dive into the "vector tile" option is the path forward. To go directly against Mongo we may have to work on a provider to TileStash. I thought I ran across a plugin/module for Mapnik that could be the starting point. I'm going to dig into this one unless someone else wants to take it.

**Comment by garnertb** [comment]
Yes, the number of features is my main concern here.  

I've assigned the task to you.  I don't think we need to actually implement this in the near term, but I'd feel better with our approach if we have a solid plan.
